//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }

        public Customer(string a, string b, string c, string d, string e, string f, string g)
        {
            this.CustomerId = a;
            this.Name = b;
            this.Description = c;
            this.Address = d;
            this.Phone = e;
            this.Email = f;
            this.ShopId = g;
        }
    
        public string CustomerId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ShopId { get; set; }
    
        public virtual Shop Shop { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
