//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPicture
    {
        public int MasterId { get; set; }
        public int ProductId { get; set; }
        public string Urls { get; set; }
    
        public virtual DetailedProduct DetailedProduct { get; set; }
        public virtual MasterProduct MasterProduct { get; set; }
    }
}
