//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public Shop()
        {
            this.Categories = new HashSet<Category>();
            this.Conversations = new HashSet<Conversation>();
            this.Customers = new HashSet<Customer>();
            this.Entities = new HashSet<Entity>();
            this.Orders = new HashSet<Order>();
            this.Products = new HashSet<Product>();
            this.Responses = new HashSet<Respons>();
            this.ShopUsers = new HashSet<ShopUser>();
            this.TemplateProducts = new HashSet<TemplateProduct>();
            this.PromotionInfoes = new HashSet<PromotionInfo>();
            this.Posts = new HashSet<Post>();
        }
    
        public string Id { get; set; }
        public string ShopName { get; set; }
        public string FbToken { get; set; }
        public string BannerImg { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int ReplyMode { get; set; }
        public int CommentMode { get; set; }
    
        public virtual ICollection<Category> Categories { get; set; }
        public virtual ICollection<Conversation> Conversations { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Entity> Entities { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Respons> Responses { get; set; }
        public virtual ICollection<ShopUser> ShopUsers { get; set; }
        public virtual ICollection<TemplateProduct> TemplateProducts { get; set; }
        public virtual ICollection<PromotionInfo> PromotionInfoes { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}
